services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_DATABASE=myDatabase
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=admin
    volumes:
      - database:/var/lib/mysql/data
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]


  java:
    image: java
    build:
      context: .java/
      dockerfile: Dockerfile
    container_name: java
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/superheroes
      - spring.datasource.username=sa
      - spring.datasource.password=admin
    ports:
      - "8448:8448"
    networks:
      - network
    healthcheck:
      test: curl http://localhost:8448/actuator/health  
      interval: 10s
      timeout: 3s
      retries: 10
      
  angular:
    image: angular
    build: 
      context: angular/
      dockerfile: Dockerfile
    container_name: angular
    depends_on:
      java:
        condition: service_healthy
    ports:
      - 8000:80
    environment:
      - BACKEND_URL=http://localhost:8448

networks:
  network:

volumes:
  database:
